### ISSUE TITLE
多语言配置错误

### ISSUE THREAD

**Issue by H1tori-a** [OWLUnion/Library#2]
languages中的语言选项目前为
English
en-US

而正确的语言选项应为
简体中文
English

最后祝贵服早日超过没有国际化英文化的猫子服务器

**Comment by H1tori-a** [comment]
English Ver

The language options in languages are currently
English
en-US

The correct language option should be
简体中文
English

Finally, I wish your server an early surpass of "Neko Dream" without international British culture

**Comment by Kupars** [comment]
已修复。感谢支持
