### ISSUE TITLE
OWL Foundation 中的语法错误

### ISSUE THREAD

**Issue by H1tori-a** [OWLUnion/Library#3]
OWL Foundation 是管理玩家赞助的平台。自从2022年11月 OWL 政府开启赞助渠道起，OWL 基金会陆续收到多位玩家的赞助，我们对此深表感谢。玩家赞助的资金将全部被用来建设 OWL Server。以下是截至2023年10月3日的玩家赞助明细和资金使用情况。未知名字的玩家已使用收款页面的不完全名称代替。如果名字或款项有误，请联系我们。

我更改为

OWL Foundation 是管理玩家赞助的平台。自从2022年11月 OWL 政府开启赞助渠道起，OWL Foundation 陆续收到多位玩家的赞助，我们对此深表感谢。玩家赞助的资金将全部被用来建设 OWL Server。以下是截至2023年10月21日的玩家赞助明细和资金使用情况。未知名字的玩家已使用收款页面的不完全名称代替。如果名字或款项有误，请联系我们。

a.我更改 2023年10月3日 为 2023年10月21日
b.为了使结构一致，我更改 OWL 基金会 为 OWL Foundation

懒得提交Pull requests，请自行更改

最后祝贵服早日超过猫子服务器和hypixel成为国际第一服务器

**Comment by Kupars** [comment]
已修复。感谢支持。
