### ISSUE TITLE
英文语法错误

### ISSUE THREAD

**Issue by H1tori-a** [OWLUnion/Library#5]
在 https://lib.kupars.top/wiki/flags-icons.html 中
依照贵服这个文档的语法
所有英文都需要在左右两边加空格
而此文档大多数未加
但是个人觉得喵之梦那些人看不出来，因为他们没贵服那么懂英文，所以可以不做更改

**Comment by Kupars** [comment]
您好，OWL Library 的原稿使用 Word 编写，其中我们使用的字体为中英文之间自动添加了合适的间距。我们将其复制过来，但因为时间不够，并未在中英文之间添加空格。这不影响玩家对内容的理解，但影响文章的美观程度。我们会尽快修复此问题。感谢您的反馈！
