### ISSUE TITLE
XYZ公社 名称错误

### ISSUE THREAD

**Issue by H1tori-a** [OWLUnion/Library#6]
在https://lib.kupars.top/wiki/flags-icons.html
最后一句
美丽的天空舒适、柔和、梦幻，代表着OWL Server、XY公社和Laocao Server以及更多的服务器的平等、多元与和平。
XY公社应该为XYZ公社
此外
按照贵服风格应该在OWL Server、XY公社和Laocao Server两面加空格
不得不说，贵服的英文水平还是比喵之梦高

**Comment by zhangzeng2** [comment]
有空再看，懒

**Comment by AlexXuCN** [comment]
谢谢关心:D 既然有GitHub账号你可以考虑pull request

**Comment by AlexXuCN** [comment]
蛤？才发现这是碘粉綿

**Comment by H1tori-a** [comment]
你好
懒得pull request
