### ISSUE TITLE
多处待改进的地方

### ISSUE THREAD

**Issue by Siaospeed** [OWLUnion/Library#9]
1. 将代码许可与文字许可分开：如代码使用MIT，Lib网页内的文字使用共享创意BY-NC-ND。你必须注意：MIT是针对软件开发的许可证，如果执意要对网页内的文字采用，请考虑LICENSE无效的可能。
2. 在GitHub仓库，加入https://lib.kupars.top/ 的网页链接，GitHub提供了这么一个功能，好像是叫所谓的仓库的官网，建议设置。

**Comment by AlexXuCN** [comment]
那文字的LICENSE我怎么处理呢…?

**Comment by Siaospeed** [comment]
在lib那里改
![image](https://github.com/OWLUnion/Library/assets/76827728/6825ec6e-fc88-48d7-9b08-6b637b9a3dff)
这是维基百科的写法示例

**Comment by Siaospeed** [comment]
![image](https://github.com/OWLUnion/Library/assets/76827728/8af925a3-1260-4022-a270-8e02b184491a)
简体中文示例

**Comment by AlexXuCN** [comment]
第二个问题解决了 第一个我也不知道怎么放上去好看 你可以pr 但是我要睡觉了
